# Generated by Django 4.2.6 on 2023-10-19 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('dia_de_reunion', models.CharField(blank=True, choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miercoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sabado'), ('DOMINGO', 'Domingo')], default='', max_length=10, null=True)),
                ('hora_reunion', models.TimeField(blank=True, default='', null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('anfitrion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anfitrion', to='personas.persona')),
                ('auxiliar', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auxiliar', to='personas.persona')),
                ('lider', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider', to='personas.persona')),
            ],
        ),
    ]
