# Generated by Django 4.2.6 on 2023-10-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('MUJER', 'Mujer'), ('HOMBRE', 'Hombre')], max_length=6)),
                ('direccion', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('telefono_movil', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('telefono_casa', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('estatus', models.CharField(choices=[('AMIGO', 'Amigo'), ('PASIVO', 'Pasivo'), ('ACTIVO', 'Activo')], default='AMIGO', max_length=10)),
            ],
        ),
    ]
