# Generated by Django 4.2.6 on 2023-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_persona_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('UNION LIBRE', 'Union Libre'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], max_length=15, null=True),
        ),
    ]
