# Generated by Django 4.2.6 on 2023-10-20 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_persona_estado_civil'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='bautismo_en_agua',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='conyuge',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conyuge_del_otro', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='experiencia_ministerial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_bautismo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_conversion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_matrimonio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='grupo_social',
            field=models.CharField(blank=True, choices=[('DAMAS', 'Damas'), ('VARONES', 'Varones'), ('JÓVENES', 'Jóvenes'), ('ADOLESCENTES', 'Adolescentes'), ('NIÑOS', 'Niños')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='iglesia_bautismo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='madre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijo_de_la_madre', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='motivo_de_alta',
            field=models.CharField(blank=True, choices=[('CAPTURA_INICIAL', 'Captura Inicial'), ('TRASLADO', 'Traslado'), ('INCORPORACION', 'Incorporación'), ('OTRO', 'Otro')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='padre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijo_del_padre', to='personas.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('UNION LIBRE', 'Union Libre'), ('SEPARADO', 'Separado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUDO', 'Viudo(a)')], max_length=15, null=True),
        ),
    ]
